# Generated by Django 3.1.1 on 2020-09-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='fio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamer',
            name='game_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamer',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
