# Generated by Django 3.1.1 on 2020-09-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_gamer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InGameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_game', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_killer', to='back.gamer')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_target', to='back.gamer')),
            ],
        ),
    ]
